

CHECKED_BONES = {
	{name = "SKEL_Pelvis", hash = 0x2E28 },
	{name = "SKEL_L_Thigh", hash = 0xE39F },
	{name = "SKEL_L_Calf", hash = 0xF9BB},
	{name = "SKEL_L_Foot", hash = 0x3779},
    {name = "SKEL_L_Toe0", hash = 0x83C },
    {name = "SKEL_R_Thigh", hash = 0xCA72 },
	{name = "SKEL_R_Calf", hash = 0x9000 },
	{name = "SKEL_R_Foot", hash = 0xCC4D },
	{name = "SKEL_R_Toe0", hash = 0x512D },
	{name = "SKEL_L_Clavicle", hash = 0xFCD9 },
	{name = "SKEL_L_UpperArm", hash = 0xB1C5 },
	{name = "SKEL_L_Forearm", hash = 0xEEEB },
    {name = "SKEL_L_Hand", hash = 0x49D9 },
    {name = "SKEL_R_Clavicle", hash = 0x29D2 },
	{name = "SKEL_R_UpperArm", hash = 0x9D4D },
	{name = "SKEL_R_Forearm", hash = 0x6E5C },
    {name = "SKEL_R_Hand", hash = 0xDEAD },
    {name = "SKEL_Neck_1", hash = 0x9995 },
    {name = "SKEL_Head", hash = 0x796E },
    {name = "SPR_L_Breast", hash = 0xFC8E },
	{name = "SPR_R_Breast", hash = 0x885F }
}

PAIN_THRESHOLD_BEFORE_SHOCK = 50

WOUND_TYPES = {
	SMALL_CONTUSION      = {name = "Small Contusion"         , pain_level = 0, bleeding = 0, heal_time = 1200},
	CONTUSION            = {name = "Contusion"               , pain_level = 1, bleeding = 0, heal_time = 1320},
	LARGE_CONTUSION      = {name = "Large Contusion"         , pain_level = 2, bleeding = 0, heal_time = 1440},
	SMALL_LACERATION     = {name = "Small Laceration"        , pain_level = 1, bleeding = 0, heal_time = 1200},
	LACERATION           = {name = "Laceration"              , pain_level = 1, bleeding = 1},
	LARGE_LACERATION     = {name = "Large Laceration"        , pain_level = 2, bleeding = 2},
	PUNCTURE_WOUND       = {name = "Puncture Wound"          , pain_level = 3, bleeding = 3},
	LARGE_PUNCTURE_WOUND = {name = "Large Puncture Wound"    , pain_level = 5, bleeding = 5},
	FIRST_DEGREE_BURN    = {name = "First Degree Burn"       , pain_level = 2, bleeding = 0, heal_time = 1440},
	SECOND_DEGREE_BURN   = {name = "Second Degree Burn"      , pain_level = 5, bleeding = 0, heal_time = 2400},
	THIRD_DEGREE_BURN    = {name = "Third Degree Burn"       , pain_level = 1, bleeding = 0},
	INFECTION            = {name = "Infection"               , pain_level = 0, bleeding = 0},
	SMALL_GUN_SHOT       = {name = "Small Gun Shot Entrance" , pain_level = 3, bleeding = 1},
	MEDIUM_GUN_SHOT      = {name = "Medium Gun Shot Entrance", pain_level = 5, bleeding = 2},
	LARGE_GUN_SHOT       = {name = "Large Gun Shot Entrance" , pain_level = 6, bleeding = 3},
	SMALL_GUN_SHOT_EXIT  = {name = "Small Gun Shot Exit"     , pain_level = 3, bleeding = 2},
	MEDIUM_GUN_SHOT_EXIT = {name = "Medium Gun Shot Exit"    , pain_level = 5, bleeding = 3},
	LARGE_GUN_SHOT_EXIT  = {name = "Large Gun Shot Exit"     , pain_level = 6, bleeding = 5},
	BROKEN_BONE          = {name = "Broken Bone"             , pain_level = 4, bleeding = 0},
	SMALL_INCISION       = {name = "Small Incision"          , pain_level = 3, bleeding = 2},
	INCISION             = {name = "Incision"                , pain_level = 5, bleeding = 3},
	LARGE_INCISION       = {name = "Large Incision"          , pain_level = 6, bleeding = 5},
	FRACTURE             = {name = "Fracture"                , pain_level = 3, bleeding = 0}
}

ITEMS = {

	BANDAGES = {
		BANDAGE          = {name = "Bandage"},
		DRESSING         = {name = "Dressing"},
		COMPRESSION      = {name = "Compression"},
		GAUZE            = {name = "Gauze"},
		USED_BANDAGE     = {name = "Used Bandage"},
		USED_DRESSING    = {name = "Used Dressing"},
		USED_COMPRESSION = {name = "Used Compression"},
		USED_GAUZE       = {name = "Used Gauze"},
		SPLINT           = {name = "Splint"},
		NECK_BRACE       = {name = "Neck Brace"},
		TOURNIQUET       = {name = "Tourniquet"},
		STITCHING        = {name = "Stitching"},
		OLD_STITCHING    = {name = "Old Stitching"},
		ALCOHOL_PAD      = {name = "Alcohol Pad"}
	},
	INJECTABLES = {
		MORPHINE      = {name = "Morphine"},
		EPINEPHRINE   = {name = "Epinephrine"},
		SALINE_250ML  = {name = "Saline 250ml"},
		SALINE_500ML  = {name = "Saline 500ml"},
		SALINE_750ML  = {name = "Saline 750ml"},
		SALINE_1000ML = {name = "Saline 1000ml"},
		BLOOD_250ML   = {name = "Blood 250ml"},
		BLOOD_500ML   = {name = "Blood 500ml"},
		BLOOD_750ML   = {name = "Blood 750ml"},
		BLOOD_1000ML  = {name = "Blood 1000ml"},
	},
	MEDICATION = {
		PARACETAMOL = {name = "Acetaminophen"},
		ASPIRIN     = {name = "Aspirin"},
		IBUPROFEN   = {name = "Ibuprofen"}
	}

}

SHORT_TERM_EFFECTS = {

	SHOCK         = "Shock",
	ADRENALINE    = "Adrenaline",
	NO_ADRENALINE = "No Adrenaline",
	FATIGUE       = "Fatigue"

}

WEAPON_TYPES = {
	MILD_BLUNT           = 1,
	BLUNT                = 2,
	SEVERE_BLUNT         = 3,
	SHARP                = 4,
	SEVERE_SHARP         = 5,
	SMALL_CALIBER_ROUND  = 6,
	MEDIUM_CALIBER_ROUND = 7,
	LARGE_CALIBER_ROUND  = 8,
	LESS_LETHAL          = 9,
	FIRE                 = 10,
	TEETH                = 11,
	HAND                 = 12,
	ARROW                = 13,
	SEVERE_ARROW         = 14,
	EXPLOSION            = 15,
	SHOTGUN_SHELL        = 16,
	SEVERE_SHOTGUN_SHELL = 17,
	VEHICLE              = 18,
	FALL                 = 19,
	DROWNING             = 20,
	MILD_IRRITANT        = 21,
	IRRITANT             = 22,
	SEVERE_IRRITANT      = 22
}

WEAPON_HASHES = {
    {"WEAPON_UNARMED", 0xA2719263, WEAPON_TYPES.HAND},
    {"WEAPON_ANIMAL", 0xF9FBAEBE, WEAPON_TYPES.TEETH},
    {"WEAPON_COUGAR", 0x08D4BE52, WEAPON_TYPES.TEETH},
    {"WEAPON_KNIFE", 0x99B507EA, WEAPON_TYPES.SHARP},
    {"WEAPON_NIGHTSTICK", 0x678B81B1, WEAPON_TYPES.BLUNT},
    {"WEAPON_HAMMER", 0x4E875F73, WEAPON_TYPES.SEVERE_BLUNT},
    {"WEAPON_BAT", 0x958A4A8F, WEAPON_TYPES.BLUNT},
    {"WEAPON_GOLFCLUB", 0x440E4788, WEAPON_TYPES.BLUNT},
    {"WEAPON_CROWBAR", 0x84BD7BFD, WEAPON_TYPES.SEVERE_ARROW},
    {"WEAPON_PISTOL", 0x1B06D571, WEAPON_TYPES.SMALL_CALIBER_ROUND},
    {"WEAPON_COMBATPISTOL", 0x5EF9FEC4, WEAPON_TYPES.SMALL_CALIBER_ROUND},
    {"WEAPON_APPISTOL", 0x22D8FE39, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_PISTOL50", 0x99AEEB3B, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_MICROSMG", 0x13532244, WEAPON_TYPES.SMALL_CALIBER_ROUND},
    {"WEAPON_SMG", 0x2BE6766B, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_ASSAULTSMG", 0xEFE7E2DF, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_ASSAULTRIFLE", 0xBFEFFF6D, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_CARBINERIFLE", 0x83BF0278, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_ADVANCEDRIFLE", 0xAF113F99, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_MG", 0x9D07F764, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_COMBATMG", 0x7FD62962, WEAPON_TYPES.LARGE_CALIBER_ROUND},
    {"WEAPON_PUMPSHOTGUN", 0x1D073A89, WEAPON_TYPES.SHOTGUN_SHELL},
    {"WEAPON_SAWNOFFSHOTGUN", 0x7846A318, WEAPON_TYPES.SHOTGUN_SHELL},
    {"WEAPON_ASSAULTSHOTGUN", 0xE284C527, WEAPON_TYPES.SHOTGUN_SHELL},
    {"WEAPON_BULLPUPSHOTGUN", 0x9D61E50F, WEAPON_TYPES.SHOTGUN_SHELL},
    {"WEAPON_STUNGUN", 0x3656C8C1, WEAPON_TYPES.LESS_LETHAL},
    {"WEAPON_SNIPERRIFLE", 0x05FC3C11, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_HEAVYSNIPER", 0x0C472FE2, WEAPON_TYPES.LARGE_CALIBER_ROUND},
    {"WEAPON_REMOTESNIPER", 0x33058E22, WEAPON_TYPES.MEDIUM_CALIBER_ROUND},
    {"WEAPON_GRENADELAUNCHER", 0xA284510B, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_GRENADELAUNCHER_SMOKE", 0x4DD2DC56},
    {"WEAPON_RPG", 0xB1CA77B1, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_PASSENGER_ROCKET", 0x166218FF, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_AIRSTRIKE_ROCKET", 0x13579279, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_STINGER", 0x687652CE, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_MINIGUN", 0x42BF8A85, WEAPON_TYPES.LARGE_CALIBER_ROUND},
    {"WEAPON_GRENADE", 0x93E220BD, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_STICKYBOMB", 0x2C3731D9, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_SMOKEGRENADE", 0xFDBC8A50, WEAPON_TYPES.MILD_IRRITANT},
    {"WEAPON_BZGAS", 0xA0973D5E, WEAPON_TYPES.SEVERE_IRRITANT},
    {"WEAPON_MOLOTOV", 0x24B17070, WEAPON_TYPES.FIRE},
    {"WEAPON_FIREEXTINGUISHER",  0x060EC506},
    {"WEAPON_PETROLCAN", 0x34A67B97},
    {"WEAPON_DIGISCANNER", 0xFDBADCED},
    {"WEAPON_BRIEFCASE", 0x88C78EB7},
    {"WEAPON_BRIEFCASE_02", 0x01B79F17},
    {"WEAPON_BALL", 0x23C9F95C, WEAPON_TYPES.MILD_BLUNT},
    {"WEAPON_FLARE",  0x497FACC3, WEAPON_TYPES.FIRE},
    {"WEAPON_VEHICLE_ROCKET", 0xBEFDC581, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_BARBED_WIRE", 0x48E7B178, WEAPON_TYPES.SHARP},
    {"WEAPON_DROWNING", 0xFF58C4FB, WEAPON_TYPES.DROWNING},
    {"WEAPON_DROWNING_IN_VEHICLE", 0x736F5990, WEAPON_TYPES.DROWNING},
    {"WEAPON_BLEEDING", 0x8B7333FB},
    {"WEAPON_ELECTRIC_FENCE", 0x92BD4EBB},
    {"WEAPON_EXPLOSION", 0x2024F4E8, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_FALL", 0xCDC174B0, WEAPON_TYPES.FALL},
    {"WEAPON_EXHAUSTION", 0x364A29EC},
    {"WEAPON_HIT_BY_WATER_CANNON", 0xCC34325E, WEAPON_TYPES.BLUNT},
    {"WEAPON_RAMMED_BY_CAR", 0x07FC7D7A, WEAPON_TYPES.VEHICLE},
    {"WEAPON_RUN_OVER_BY_CAR", 0xA36D413E, WEAPON_TYPES.VEHICLE},
    {"WEAPON_HELI_CRASH", 0x145F1012, WEAPON_TYPES.EXPLOSION},
    {"WEAPON_FIRE", 0xDF8E89EB, WEAPON_TYPES.FIRE}
}