
PLAYER = {
    BLOOD_PRESSURE = {SYSTOLIC = 100, DIASTOLIC = 75},
    PAIN_LEVEL = 0,
    WOUNDS = {},
    BANDAGES = {},
    SHORTERM_EFFECTS = {},
    LONGTERM_EFFECTS  = {},
    PERMANENT_EFFECTS = {}
}